version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: temp
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ../
      dockerfile: ./docker/coeus_backend_base.Dockerfile
      args:
        - PROJECT_DIR=/app
    volumes:
      - workspace:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=temp
      - POSTGRES_HOST=postgres
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  postgres-data:
  workspace:
